[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rcc-non-linear"
version = "0.2.0"
description = "Nonlinear analysis tools for RCC structures"
authors = [{ name = "Abinash Mandal" }]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "reportlab",
    "importlib_resources; python_version < '3.9'",
]

[project.optional-dependencies]
opensees = [
    "openseespy; python_version == '3.8'",
    "opsvis; python_version == '3.8'",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["rcc_non_linear*"]

[tool.setuptools.package-data]
"rcc_non_linear.concrete_models.data" = ["*.csv"]
